version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - twitter_net
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@twitter_postgres:5432/twitter_db?sslmode=disable", "up" ]
    depends_on:
      postgres-db:
        condition: service_started

  postgres-db:
    container_name: twitter_postgres
    image: postgres
    environment:
      POSTGRES_DB: twitter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_SSL_MODE: disable
    volumes:
      - twitter_database_volume:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - twitter_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twitter_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-db:
    container_name: twitter_redis
    image: redis
    ports:
      - "6375:6379"
    networks:
      - twitter_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend-app:
    container_name: twitter_app
    build: .
    networks:
      - twitter_net
    volumes:
      - ./media:/app/media
      - ./internal/pkg/config/auth.conf:/app/internal/pkg/config/auth.conf
      - ./internal/pkg/config/auth.csv:/app/internal/pkg/config/auth.csv
    ports:
      - "7777:7777"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_started
    restart: unless-stopped

networks:
  twitter_net:
    driver: bridge

volumes:
  twitter_database_volume: