version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - twitter_net
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@twitter_postgres:5432/twitter_db?sslmode=disable", "up" ]
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: twitter_postgres
    image: postgres
    environment:
      POSTGRES_DB: twitter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_SSL_MODE: disable
    volumes:
      - twitter_database_volume:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - twitter_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twitter_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-db:
    container_name: twitter_redis
    image: redis
    ports:
      - "6375:6379"
    networks:
      - twitter_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3


  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - twitter_net

  backend-app:
    container_name: twitter_app
    build: .
    networks:
      - twitter_net
    volumes:
      - ./media:/app/media
      - ./internal/pkg/config/auth.conf:/app/internal/pkg/config/auth.conf
      - ./internal/pkg/config/auth.csv:/app/internal/pkg/config/auth.csv
    ports:
      - "7777:7777"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_started
      broker:
        condition: service_started
    restart: unless-stopped

  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./k6:/k6
    command:
      run /loadTest/get.js
      run /loadTest/post.js
    depends_on:
      - app
    networks:
      - twitter_net

networks:
  twitter_net:
    driver: bridge

volumes:
  twitter_database_volume: