name: Build, Test, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_test_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Install Dependencies
        run: |
          go mod download

      - name: Run Unit Tests
        run: |
          go test ./... -v

      - name: Clone repository and Deploy to Server
        if: success() # Only run if the tests pass
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "github.com/mini-twitter" ]; then
              mkdir -p github.com/mini-twitter
            fi
            cd github.com/mini-twitter/
            docker compose down || true
            git pull origin main
            docker compose up -- build -d
          script_stop: true
          timeout: 300s




# name: Build, Push, and Deploy Docker Image

# on:
#   push:
#     branches:
#       - main

# env:
#   SERVER_HOST: ${{ secrets.SERVER_HOST }}
#   SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
#   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# jobs:
#   build_push_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Clone repository and Up project to server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ env.SERVER_HOST }}
#           username: ${{ env.SERVER_USERNAME }}
#           key: ${{ env.SSH_PRIVATE_KEY }}
#           script: |
#             if [ ! -d "github.com/mini-twitter" ]; then
#               mkdir -p github.com/mini-twitter
#             fi
#             cd github.com/mini-twitter/
#             docker compose down || true
#             git pull origin main
#             docker compose up -- build -d
#           script_stop: true
#           timeout: 300s